apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springboot-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: spring
  endpoints:
  - port: http
    path: /manage/prometheus
    interval: 15s
